// The "unified-balance wallet" starter template: a minimal, runnable app with
// Particle's Universal Accounts SDK pre-wired, optional Magic embedded wallet
// and gas-sponsorship toggles, and one small demo contract (a tip jar) that
// hands off to CRUZ's Contract Editor rather than shipping a
// second deploy path.

import { buildUniversalAccountModule, UNIVERSAL_ACCOUNT_MODULE_PATH } from "./universalAccountInit";

export interface ScaffoldConfig {
  projectName: string;
  embeddedWallet: boolean;
  gasSponsorship: boolean;
}

// `projectName` is free-text user input that gets spliced into generated
// source (index.html, App.tsx) at generation time — unescaped, it's a stored
// HTML/script-injection point in the app's own output (a `</title><script>`
// payload becomes a live tag in the shipped index.html; a `"` breaks out of a
// JS string literal in App.tsx). Neutralize the characters that matter in
// HTML/JSX text and JS string-literal contexts.
function escapeForGeneratedSource(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;")
    .replace(/\{/g, "&#123;")
    .replace(/\}/g, "&#125;");
}

const TIP_JAR_CONTRACT = `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/// @title TipJar
/// @notice Minimal demo contract for the unified-balance wallet starter: accepts
///         native-token tips and lets the owner withdraw them.
contract TipJar {
    address public immutable owner;
    uint256 public totalTipped;

    event Tipped(address indexed from, uint256 amount);
    event Withdrawn(uint256 amount);

    constructor() {
        owner = msg.sender;
    }

    function tip() external payable {
        require(msg.value > 0, "Tip must be > 0");
        totalTipped += msg.value;
        emit Tipped(msg.sender, msg.value);
    }

    function withdraw() external {
        require(msg.sender == owner, "Not owner");
        uint256 balance = address(this).balance;
        (bool ok, ) = owner.call{value: balance}("");
        require(ok, "Withdraw failed");
        emit Withdrawn(balance);
    }
}
`;

function packageJson(cfg: ScaffoldConfig): string {
  return JSON.stringify(
    {
      name: cfg.projectName,
      private: true,
      version: "0.1.0",
      type: "module",
      scripts: { dev: "vite", build: "vite build", preview: "vite preview" },
      dependencies: {
        "@particle-network/universal-account-sdk": "^2.0.3",
        ethers: "^6.13.0",
        react: "^19.2.0",
        "react-dom": "^19.2.0",
        ...(cfg.embeddedWallet ? { "magic-sdk": "^28.0.0" } : {}),
      },
      devDependencies: {
        "@vitejs/plugin-react": "^5.0.4",
        typescript: "^5.8.3",
        vite: "^7.3.1",
      },
    },
    null,
    2,
  );
}

function envExample(cfg: ScaffoldConfig): string {
  return `# Particle Network — dashboard.particle.network (enable Universal Accounts)
VITE_PARTICLE_PROJECT_ID=
VITE_PARTICLE_CLIENT_KEY=
VITE_PARTICLE_APP_ID=

# Arbitrum One RPC (a dedicated provider like Alchemy is recommended)
VITE_ARBITRUM_RPC=https://arb1.arbitrum.io/rpc
${cfg.embeddedWallet ? "\n# Magic embedded wallet — dashboard.magic.link\nVITE_MAGIC_PUBLISHABLE_KEY=\n" : ""}${
    cfg.gasSponsorship
      ? "\n# Gas sponsorship: set a Particle-configured paymaster/sponsor policy if required\nVITE_GAS_SPONSORSHIP=true\n"
      : ""
  }`;
}

function appTsx(cfg: ScaffoldConfig): string {
  return `import { useState } from "react";
import { ua } from "./lib/universalAccount";
${cfg.embeddedWallet ? 'import { Magic } from "magic-sdk";\n' : ""}${cfg.embeddedWallet ? "\nconst magic = new Magic(import.meta.env.VITE_MAGIC_PUBLISHABLE_KEY);\n" : ""}
export default function App() {
  const [balance, setBalance] = useState<number | null>(null);

  const fetchBalance = async () => {
    const assets = await ua.getPrimaryAssets();
    setBalance(assets.totalAmountInUSD);
  };

  return (
    <div style={{ fontFamily: "monospace", padding: 24 }}>
      <h1>${escapeForGeneratedSource(cfg.projectName)}</h1>
      <p>Unified balance across chains, one address, no bridging.</p>
      <button onClick={fetchBalance}>Fetch unified balance</button>
      {balance !== null && <p>Unified balance: \${balance.toFixed(2)}</p>}
    </div>
  );
}
`;
}

const README = (cfg: ScaffoldConfig) => `# ${cfg.projectName}

A chain-abstracted starter app generated by CRUZ's Chain Abstraction Studio — Universal
Accounts pre-wired via Particle Network's SDK${cfg.embeddedWallet ? ", with a Magic embedded wallet" : ""}.

## Quick start

\`\`\`bash
npm install
cp .env.example .env.local   # fill in your Particle credentials
npm run dev
\`\`\`

## What's inside

- \`src/App.tsx\` — Universal Account init + a unified-balance demo.
- \`contracts/TipJar.sol\` — a minimal demo contract. Deploy it through CRUZ's Contract Editor
  (paste the source into the Contract Editor) rather than a separate toolchain.
`;

/** Renders the full file map for this template given the chosen config. */
export function buildUnifiedWalletTemplate(config: ScaffoldConfig): Record<string, string> {
  return {
    "package.json": packageJson(config),
    ".env.example": envExample(config),
    "README.md": README(config),
    [UNIVERSAL_ACCOUNT_MODULE_PATH]: buildUniversalAccountModule({ projectName: config.projectName }),
    "src/App.tsx": appTsx(config),
    "src/main.tsx": `import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import App from "./App";

createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <App />
  </StrictMode>,
);
`,
    "index.html": `<!doctype html>
<html>
  <head><meta charset="utf-8" /><title>${escapeForGeneratedSource(config.projectName)}</title></head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`,
    "vite.config.ts": `import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({ plugins: [react()] });
`,
    "contracts/TipJar.sol": TIP_JAR_CONTRACT,
  };
}

export const UNIFIED_WALLET_TEMPLATE = {
  id: "unified-wallet",
  label: "Unified-Balance Wallet",
  description:
    "A minimal app showing one address, one balance, any chain — plus a tip-jar demo contract.",
  hasDemoContract: true,
  demoContractPath: "contracts/TipJar.sol",
} as const;
