/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScaffolderRouteImport } from './routes/scaffolder'
import { Route as InspectorRouteImport } from './routes/inspector'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as ComposerRouteImport } from './routes/composer'
import { Route as CodeAiRouteImport } from './routes/code-ai'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAiRouteImport } from './routes/api.ai'

const ScaffolderRoute = ScaffolderRouteImport.update({
  id: '/scaffolder',
  path: '/scaffolder',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectorRoute = InspectorRouteImport.update({
  id: '/inspector',
  path: '/inspector',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const ComposerRoute = ComposerRouteImport.update({
  id: '/composer',
  path: '/composer',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeAiRoute = CodeAiRouteImport.update({
  id: '/code-ai',
  path: '/code-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiRoute = ApiAiRouteImport.update({
  id: '/api/ai',
  path: '/api/ai',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/builder': typeof BuilderRoute
  '/code-ai': typeof CodeAiRoute
  '/composer': typeof ComposerRoute
  '/editor': typeof EditorRoute
  '/inspector': typeof InspectorRoute
  '/scaffolder': typeof ScaffolderRoute
  '/api/ai': typeof ApiAiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/builder': typeof BuilderRoute
  '/code-ai': typeof CodeAiRoute
  '/composer': typeof ComposerRoute
  '/editor': typeof EditorRoute
  '/inspector': typeof InspectorRoute
  '/scaffolder': typeof ScaffolderRoute
  '/api/ai': typeof ApiAiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/builder': typeof BuilderRoute
  '/code-ai': typeof CodeAiRoute
  '/composer': typeof ComposerRoute
  '/editor': typeof EditorRoute
  '/inspector': typeof InspectorRoute
  '/scaffolder': typeof ScaffolderRoute
  '/api/ai': typeof ApiAiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/builder'
    | '/code-ai'
    | '/composer'
    | '/editor'
    | '/inspector'
    | '/scaffolder'
    | '/api/ai'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/builder'
    | '/code-ai'
    | '/composer'
    | '/editor'
    | '/inspector'
    | '/scaffolder'
    | '/api/ai'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/builder'
    | '/code-ai'
    | '/composer'
    | '/editor'
    | '/inspector'
    | '/scaffolder'
    | '/api/ai'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  BuilderRoute: typeof BuilderRoute
  CodeAiRoute: typeof CodeAiRoute
  ComposerRoute: typeof ComposerRoute
  EditorRoute: typeof EditorRoute
  InspectorRoute: typeof InspectorRoute
  ScaffolderRoute: typeof ScaffolderRoute
  ApiAiRoute: typeof ApiAiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scaffolder': {
      id: '/scaffolder'
      path: '/scaffolder'
      fullPath: '/scaffolder'
      preLoaderRoute: typeof ScaffolderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspector': {
      id: '/inspector'
      path: '/inspector'
      fullPath: '/inspector'
      preLoaderRoute: typeof InspectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/composer': {
      id: '/composer'
      path: '/composer'
      fullPath: '/composer'
      preLoaderRoute: typeof ComposerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code-ai': {
      id: '/code-ai'
      path: '/code-ai'
      fullPath: '/code-ai'
      preLoaderRoute: typeof CodeAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai': {
      id: '/api/ai'
      path: '/api/ai'
      fullPath: '/api/ai'
      preLoaderRoute: typeof ApiAiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  BuilderRoute: BuilderRoute,
  CodeAiRoute: CodeAiRoute,
  ComposerRoute: ComposerRoute,
  EditorRoute: EditorRoute,
  InspectorRoute: InspectorRoute,
  ScaffolderRoute: ScaffolderRoute,
  ApiAiRoute: ApiAiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
